env_name: kitchen_continual-v4
H_total: 200
num_traj: 10
seed: 100
num_iter: 1
plan_horizon: 16
paths_per_cpu: 2
num_cpu: 16
filter:
    beta_0: 0.25
    beta_1: 0.8
    beta_2: 0.0
kappa: 5.0
gamma: 1.0
default_act: mean
visualize: True
exp_notes: 'Continual kitchen actions'