default:
    - override hydra/launcher: local

env_name: kitchen_continual-v4
H_total: 200
num_traj: 1
seed: 100
num_iter: 1
plan_horizon: 16
paths_per_cpu: 32
num_cpu: 1
filter:
    beta_0: 0.25
    beta_1: 0.8
    beta_2: 0.0
kappa: 5.0
gamma: 1.0
default_act: mean
visualize: False
exp_notes: 'Continual kitchen actions'
hydra:
    job:
        name: trajopt_${env_name}